baseurl: "https://esracom.github.io/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://esracom.github.io/flexible-jekyll" # the base hostname & protocol for your site, e.g. http://example.com
# Author Settings
author: Esra LAĞAMCIOĞLU # add your name

about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: https://twitter.com/elfsrzhra

social-linkedin: https://www.linkedin.com/in/esra-la%C4%9Famcio%C4%9Flu-028443140/
social-email: esralgmcgl@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
